eureka:
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka
spring:
  mvc:
    log-request-details: true
  cloud:
    stream:
      bindings:
        output:
          destination: yintao
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          zkNodes: localhost
    bus:
      id : 101